RubyLouvre/avalon.oniui

loading/avalon.loading.bar.html, loading/avalon.loading.doc.html, loading/avalon.loading.ex7.html, loading/avalon.loading.js
=> 新增一个自定义loading图片

README.md
=> 去哪儿UED链接修正

build-tree.sh, oniui.sublime-build, sublime-build.sh, touch/avalon.touch.ex1.html, touch/avalon.touch.js
=> 给touch事件增加一个avalon签名

oniui.sublime-build, tree/avalon.tree.js
=> 修复tree新增节点，父节点不展开的bug

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex.html, mmRouter/avalon.mmRouter.ex1.html, scrollspy/avalon.scrollspy.doc.html, scrollspy/avalon.scrollspy.ex.html, scrollspy/avalon.scrollspy.ex1.html, scrollspy/avalon.scrollspy.js
给scrollspy添加例子和接口，给mmRouter添加例子
=> 给scrollspy添加例子和接口，给mmRouter添加例子

mmRequest/avalon.mmRequest.doc.html, mmRequest/avalon.mmRequest.ex.html, mmRequest/avalon.mmRequest.ex1.html, mmRequest/avalon.mmRequest.ex2.html, mmRequest/avalon.mmRequest.ex3.html, mmRequest/mmRequest.js, mmRequest/test.js
给mmRequest添加例子，并修复getScript不能触发success的bug
=> 给mmRequest添加例子，并修复getScript不能触发success的bug

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/mmHistory.js, mmRouter/mmState.js
修复mmRouter的go不能更新url的问题，并增加使用go的例子
=> add ex for mmRouter

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex.html, mmRouter/avalon.mmRouter.ex1.html, mmRouter/avalon.mmRouter.ex2.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/avalon.mmRouter.ex4.html, mmRouter/mmHistory.js, mmRouter/mmRouter.js, mmRouter/mmState.js
=> fix url & params bug

mmRouter/avalon.mmRouter.js, mmRouter/mmHistory.js, mmRouter/mmPromise.js, mmRouter/mmRouter.js, mmRouter/mmState.js
修复promise.all的bug，修改history写历史接口
=> 修复promise.all的bug，修改history写历史接口

pages/library/index.html
=> 修正初次进入Library页无法显示内容的Bug

index.html, mmRouter/avalon.mmRouter.ex7.html, pages/library/index.html
=> fix ex bug

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex7.html, mmRouter/mmRouter.js, mmRouter/mmState.js
校正onUpdate的触发时机为reload=true或者params or query变化的时候
=> 校正onUpdate的触发时机

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/mmRouter.js, mmRouter/mmState.js
1，校正onUpdate的触发时机为reload=true或者params or query变化的时候
2，恢复每个状态独立享有一个params参数，所有state共有一个query参数
=> 修改params & query变化逻辑

mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/avalon.mmRouter.ex8.html, mmRouter/js/app.js, mmRouter/js/model/model.js, mmRouter/js/views/footer.html, mmRouter/js/views/list.html, mmRouter/learn.json, mmRouter/mmRouter.js, mmRouter/mmState.js, mmRouter/todomvc-app-css/index.css, mmRouter/todomvc-common/base.css, mmRouter/todomvc-common/base.js, mvc.sh, sublime-build.sh
add todomvc demo use avalon js && oniui
=> add todomvc demo use avalon js && oniui

camera/avalon.camera.js, carousel/avalon.carousel.css, carousel/avalon.carousel.doc.html, carousel/avalon.carousel.ex1.html, carousel/avalon.carousel.ex2.html, carousel/avalon.carousel.ex3.html, carousel/avalon.carousel.ex4.html, carousel/avalon.carousel.ex5.html, carousel/avalon.carousel.ex6.html, carousel/avalon.carousel.ex7.html, carousel/avalon.carousel.html, carousel/avalon.carousel.js, carousel/avalon.carousel.scss, colorpicker/avalon.colorpicker.js
原先只能配置图片，现已增加配置自定义模板功能，更加强大。详情参考：`/avalon.oniui/carousel/avalon.carousel.ex7.html`
=> carcousel 增加自定义模板功能

dropdown/avalon.dropdown.js, layout/avalon.layout.css, layout/avalon.layout.doc.html, layout/avalon.layout.ex1.html, layout/avalon.layout.ex2.html, layout/avalon.layout.ex3.html, layout/avalon.layout.ex4.html, layout/avalon.layout.js, layout/avalon.layout.scss
DropDown组件：
修正一个IE6-8下的JS错误。
Layout：
1.新增百分比尺寸配置的支持。
2.Bug修正。
3.新增一个例子。
4.修改文档。
=> 修正IE6-8下Dropdown组件的一个JS错误；增强Layout及bug修复

mmRouter/README.md, mmRouter/js/app.js, mvc.sh
=> change mmRouter README

mmRouter/README.md, mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/mmHistory.js, mmRouter/mmState.js
1,fix query undefine bug
2,add ignoreChange config for state
3,keep url hash for html5 mode while first loading
=> fix bug & add method

chameleon/oniui-common.css, chameleon/oniui-common.scss, rating/avalon.rating.ex.html, rating/avalon.rating.js
=> fix rating ico bug

mmRouter/README.md, mmRouter/mmState.js
=> 修复mmRouter一个潜在的不友好接口

mmRequest/mmRequest.js, mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.js, mmRouter/mmState.js, mmRouter/ppt/model/ppt.js, tree/avalon.tree.edit.html
去掉mmRequest & mmState的define module name，让其在requirejs上可以正常运行
=> 去掉mmRequest & mmState的define module name

index.html, style/avalon.index.css
=> 添加更明显的pack tool入口

mmRouter/README.md, mmRouter/avalon.mmRouter.doc.html, mmRouter/avalon.mmRouter.ex3.html, mmRouter/mmHistory.js, position/avalon.position.doc.html, position/avalon.position.ex.html
=> 修改history接口

flipswitch/avalon.flipswitch.doc.html, flipswitch/avalon.flipswitch.ex.html, flipswitch/avalon.flipswitch.js
=> 提升flipswitch的用户体验

flipswitch/avalon.flipswitch.doc.html, flipswitch/avalon.flipswitch.ex.html, flipswitch/avalon.flipswitch.js
在ms-repeat情形下，由于repeat异步延时，导致未能获取到$proxy.el，因此加上一个avalon.nextTick
=> fix ms-repeat duplex bug

flipswitch/avalon.flipswitch.js
=> fix flipswitch duplex bug

button/avalon.button.js, carousel/avalon.carousel.js
button: 修复设置disabled为非布尔型时问题
carousel: 版本号变化为0.0.2
=> button & carousel

carousel/avalon.carousel.css, carousel/avalon.carousel.ex.html, carousel/avalon.carousel.ex1.html, carousel/avalon.carousel.ex2.html, carousel/avalon.carousel.ex3.html, carousel/avalon.carousel.ex4.html, carousel/avalon.carousel.ex5.html, carousel/avalon.carousel.ex6.html, carousel/avalon.carousel.ex7.html, carousel/avalon.carousel.html, carousel/avalon.carousel.js, carousel/avalon.carousel.scss, dropdown/avalon.dropdown.ex12.html, dropdown/avalon.dropdown.js, resizable/avalon.resizable.js
carousel:
修复IE6下图片显示BUG
将示例中的图片移到cdn，加快访问速度
=> 修复carousel IE6 bug

datepicker/avalon.datepicker.html, tooltip/avalon.tooltip.css, tooltip/avalon.tooltip.doc.html, tooltip/avalon.tooltip.ex7.html, tooltip/avalon.tooltip.js, tooltip/avalon.tooltip.scss
datapicker：增加日期title
tooltip：增加zIndex配置项，默认是body直接子元素中的最大z-index值
=> datapicker：增加日期title

textbox/avalon.textbox.doc.html, textbox/avalon.textbox.ex7.html, textbox/avalon.textbox.js
textbox：新增自适应高度，并可以配置自适应时的minHeight/maxHeight。添加例子，更新文档。
=> textbox：新增自适应高度

smartgrid/avalon.smartgrid.css, smartgrid/avalon.smartgrid.doc.html, smartgrid/avalon.smartgrid.ex13.html, smartgrid/avalon.smartgrid.html, smartgrid/avalon.smartgrid.js, smartgrid/avalon.smartgrid.scss
smartgrid: 0.0.2 增加自定义列的显示/隐藏，添加示例13和文档
=> smartgrid: 0.0.2 增加自定义列的显示/隐藏

carousel/avalon.carousel.css, carousel/avalon.carousel.scss
=> carousel：修复样式错误

smartgrid/avalon.smartgrid.doc.html, smartgrid/avalon.smartgrid.js
selectable可配置宽度
修复配置selectable时，控制列显隐问题
=> smartgrid：selectable可配置宽度

smartgrid/avalon.smartgrid.js
=> smartgrid：修复有些情况下宽度超出父元素

smartgrid/avalon.smartgrid.js
smartgrid: 设置百分比宽度的列将响应window resize来适应父容器宽度的变化
=> smartgrid: 设置百分比宽度的列将响应window resize来适应父容器宽度的变化

live/avalon.live.js
1，修改执行时回收检测判定逻辑
2，增加定时自动检测回收逻辑 - 20分钟，针对长时间运行的spa应用
=> 修复live组件内存泄露

mmRouter/mmHistory.js
=> 修复不能同步lastpath的bug

index.html, pages/index/scripts/models.js, pages/index/views/widgets/list.html
=> 去掉uploader组件文档

datepicker/avalon.datepicker.js, dialog/avalon.dialog.ex1.html, dropdownlist/avalon.dropdownlist.js, i18n/avalon.datepicker.lang-en.js, i18n/avalon.pager.lang-en.js, kindeditor/avalon.kindeditor.js, touch/avalon.iscroll.js, touch/nscroll.js
=> 去掉有.js后缀的依赖

smartgrid/avalon.smartgrid.js
=> samrtgrid：render时修正宽度

checkboxlist/avalon.checkboxlist.html, datepicker/avalon.datepicker.html, miniswitch/avalon.miniswitch.html, simplegrid/avalon.simplegrid.html, smartgrid/avalon.smartgrid.js, spinner/avalon.spinner.ex1.html, spinner/avalon.spinner.html, textbox/avalon.textbox.ex1.html, textbox/avalon.textbox.ex3.html, textbox/avalon.textbox.html
去掉多余警告信息：如ms-title应改为ms-attr-title等
=> 去掉主要组件多余警告信息

spinner/avalon.spinner.js
=> spinner：添加可输入负数功能

button/avalon.button.ex1.html, button/avalon.button.ex2.html, button/avalon.button.ex3.html, button/avalon.button.ex4.html, switchdropdown/avalon.switchdropdown.ex1.html, switchdropdown/avalon.switchdropdown.ex2.html, switchdropdown/avalon.switchdropdown.ex3.html, switchdropdown/avalon.switchdropdown.ex4.html, switchdropdown/avalon.switchdropdown.html
button：修复图标不显示
switchdropdown：修复require问题
=> 修复button/switchdropdown

mmRequest/avalon.mmRequest.ex.html, mmRequest/avalon.mmRequest.ex1.html, mmRequest/avalon.mmRequest.ex2.html, mmRequest/avalon.mmRequest.ex3.html, pages/index/scripts/models.js
=> mmrequest：添加到官网

spinner/avalon.spinner.js
=> spinner：修复输入超出限制时数据未同步

pages/index/scripts/models.js, spinner/avalon.spinner.js, textbox/avalon.suggest.js
spinner & textbox: 修复输入/选择时数据不同步的情况
官网：添加fileuploader ex6至文档
=> spinner & textbox: 修复输入/选择时数据不同步的情况

tab/avalon.tab.doc.html, tab/avalon.tab.ex9.html, tab/avalon.tab.html, tab/avalon.tab.js
tab：修复slider状态下箭头不出现的问题，增加sliderStep配置项控制每次切换的距离
=> tab：修复slider状态下箭头不出现的问题，增加sliderStep配置项控制每次切换的距离

pages/index/scripts/models.js
=> 官网：修复IE8下mmRouter显示问题

dropdown/avalon.dropdown.js
=> dropdown: 修复setLabelTitle

dropdown/avalon.dropdown.js
=> dropdown：去掉filter中多余判断

simplegrid/avalon.simplegrid.doc.html, style/avalon.doc.css, style/avalon.doc.scss
=> 官网：修复simplegird表格显示问题

smartgrid/avalon.smartgrid.js
smartgrid：修复checkbox选中时只有复选框的底色变化
=> smartgrid：修复checkbox选中时只有复选框的底色变化

datepicker/lunarCalculate.html
=> datepicker: 优化假日数据生成工具

smartgrid/avalon.smartgrid.ex13.html, smartgrid/avalon.smartgrid.js
=> smartgrid: 自定义列显示隐藏之后宽度会自动适应

smartgrid/avalon.smartgrid.js
smartgrid: setColumns之后也自动调整宽度
=> smartgrid: setColumns之后也自动调整宽度

breadcrumb/avalon.breadcrumb.css, breadcrumb/avalon.breadcrumb.doc.html, breadcrumb/avalon.breadcrumb.ex.html, breadcrumb/avalon.breadcrumb.html, breadcrumb/avalon.breadcrumb.js, breadcrumb/avalon.breadcrumb.scss, pages/index/scripts/models.js
=> add breadcrumb

smartgrid/avalon.smartgrid.ex13.html
=> smartgrid修复样例中代码高亮没同步

mmRouter/mmPromise.js
添加mmPromise.js至mmRouter，以修复官网错误
=> 添加mmPromise.js至mmRouter，以修复官网错误

dropdown/avalon.dropdown.doc.html, dropdown/avalon.dropdown.ex11.html, dropdown/avalon.dropdown.js, pages/index/scripts/index.js, test/elves.config, test/smartgrid/smartgrid.ex2.case.js
=> dropdown: 新异步传值方式

tree/avalon.tree.js
=> 修复tree nodeCreated触发两次的bug

validation/avalon.validation.ex15.html
validation: 添加textbook suggest示例
=> validation: 添加textbook suggest示例

scrollbar/avalon.scrollbar.ex.html, scrollbar/avalon.scrollbar.ex1.html, scrollbar/avalon.scrollbar.ex2.html, scrollbar/avalon.scrollbar.ex3.html, scrollbar/avalon.scrollbar.ex4.html, scrollbar/avalon.scrollbar.ex5.html, scrollbar/avalon.scrollbar.js
修复scrollbarIE 8及以下不可点的bug，以及修复把宽、高设置成0的bug
=> 修复scrollbarIE 8及以下不可点的bug，以及修复把宽、高设置成0的bug

lazyload/avalon.lazyload.ex5.html, lazyload/avalon.lazyload.js, pages/index/scripts/models.js
=> lazyload: 修复load多次

dropdown/avalon.dropdown.ex16.html, pages/index/scripts/models.js
=> 添加dropdown联动列表样例

README.md
=> 添加请使用1.4.*或以下版本的avalon的提示

dropdown/avalon.dropdown.js
dropdown: 修复一些情况下当用户选择option时，选项数据会改变
=> dropdown: 修复一些情况下当用户选择option时，选项数据会改变

textbox/avalon.suggest.css, textbox/avalon.suggest.js, textbox/avalon.suggest.scss, textbox/avalon.textbox.css, textbox/avalon.textbox.scss
=> textbox: 修复ms-if控制显隐时样式错误

datepicker/avalon.datepicker.doc.html, datepicker/avalon.datepicker.js
修复datepicker 存在timer时无法设置width，并且不触发blur
=> 修复datepicker 存在timer时无法设置width，并且不触发blur

resizable/avalon.resizable.js
resizable: 修复draggable时，鼠标脱离元素不能拖动
=> resizable: 修复draggable时，鼠标脱离元素不能拖动

draggable/avalon.draggable.js
=> bugfix: draggable嵌套导致子元素无法拖动

mmRouter/avalon.mmRouter.ex3.html, mmRouter/edit.js, mmRouter/mmState.js
=> 新增stateUrl

datepicker/avalon.datepicker.css, datepicker/avalon.datepicker.html, datepicker/avalon.datepicker.js, datepicker/avalon.datepicker.scss, draggable/avalon.draggable.js, dropdown/avalon.dropdown.js, smartgrid/avalon.smartgrid.css, smartgrid/avalon.smartgrid.html, smartgrid/avalon.smartgrid.js, smartgrid/avalon.smartgrid.scss, spinner/avalon.spinner.js
涉及组件: datepicker, dropdown, spinner, draggable, smartgrid
=> merge i18n版本中发现的组件bug和优化

button/avalon.button.ex1.html, button/avalon.button.ex2.html
=> fix iconfont 编码错误

datepicker/avalon.datepicker.html
fix(date picker): 修复year/month dropdown取值不正确
=> fix(date picker): 修复year/month dropdown取值不正确
